# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:light
#     text_representation:
#       extension: .py
#       format_name: light
#       format_version: '1.5'
#       jupytext_version: 1.16.4
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

# # MES — 03_validate
#
# Runs the full validation suite and writes `benchmarks.md`.
# Pulls processed data + ONNX models from HF.

# +
import os, json, io
from pathlib import Path

os.system("pip install -q --upgrade pip")
os.system("pip install -q numpy scipy scikit-learn pyriemann 'huggingface_hub>=0.24' onnxruntime pandas")
# -

# +
import numpy as np
import pandas as pd
import onnxruntime as ort
from sklearn.model_selection import StratifiedKFold, GroupKFold
from huggingface_hub import snapshot_download, login, HfApi

HF_TOKEN = os.environ["HF_TOKEN"]
HF_USER  = os.environ.get("HF_USERNAME", "abachu2005")
HF_DATASET_REPO = os.environ.get("HF_DATASET_REPO", f"{HF_USER}/mes-eeg-processed")
HF_MODEL_REPO   = os.environ.get("HF_MODEL_REPO",   f"{HF_USER}/mes-models")
login(token=HF_TOKEN)
api = HfApi(token=HF_TOKEN)
# -

# +
ds_dir = Path(snapshot_download(repo_id=HF_DATASET_REPO, repo_type="dataset", token=HF_TOKEN))
m_dir  = Path(snapshot_download(repo_id=HF_MODEL_REPO,   token=HF_TOKEN))
print("datasets:", sorted(p.name for p in ds_dir.iterdir())[:5])
print("models:",   sorted(p.name for p in m_dir.iterdir()))
# -

# +
TARGET_T = 750
target_classes = {"right_hand": 1, "rest": 0}

def load_subset(prefix):
    files = sorted(ds_dir.glob(f"{prefix}*.parquet"))
    rows = []
    for f in files:
        df = pd.read_parquet(f)
        for _, r in df.iterrows():
            if r["label"] not in target_classes:
                continue
            X = np.frombuffer(r["data"], dtype="float32").reshape(r["n_channels"], r["n_times"])
            n = X.shape[1]
            if n >= TARGET_T:
                X = X[:, :TARGET_T]
            else:
                X = np.concatenate([X, np.zeros((X.shape[0], TARGET_T-n), dtype="float32")], 1)
            rows.append({"X": X, "y": target_classes[r["label"]], "subject": r["subject"]})
    return rows

def evaluate_classifier(rows, sess):
    if not rows:
        return None
    X = np.stack([r["X"] for r in rows])
    y = np.array([r["y"] for r in rows])
    # ONNX expects (batch, n_features) for the Riemannian pipeline (already in TS space).
    # For EEGNet it expects (batch, n_ch, n_times).
    in_meta = sess.get_inputs()[0]
    ndim = len(in_meta.shape)
    if ndim == 2:
        # Riemannian path - compute features here
        from pyriemann.estimation import Covariances
        from pyriemann.tangentspace import TangentSpace
        cov = Covariances("oas").fit_transform(X)
        ts = TangentSpace(metric="riemann").fit_transform(cov)
        feed = ts.astype(np.float32)
    else:
        feed = X.astype(np.float32)
    pred = sess.run(None, {in_meta.name: feed})[0]
    if pred.ndim == 2:
        yhat = pred.argmax(1)
        proba = pred[:, 1] if pred.shape[1] >= 2 else pred[:, 0]
    else:
        yhat = (pred > 0.5).astype(int)
        proba = pred.ravel()
    acc = float((yhat == y).mean())
    from sklearn.metrics import roc_auc_score, brier_score_loss
    try:
        auc = float(roc_auc_score(y, proba))
    except Exception:
        auc = float("nan")
    brier = float(brier_score_loss(y, np.clip(proba, 0, 1)))
    return {"n": len(y), "acc": acc, "auc": auc, "brier": brier}
# -

# +
results = {"per_dataset": {}, "models": []}
for model_file in sorted(m_dir.glob("*.onnx")):
    print("Evaluating", model_file.name)
    sess = ort.InferenceSession(str(model_file), providers=["CPUExecutionProvider"])
    by_ds = {}
    for prefix in ("physionet_", "bci_iv_2a_", "liu2024_"):
        rows = load_subset(prefix)
        r = evaluate_classifier(rows, sess)
        if r:
            by_ds[prefix.rstrip("_")] = r
    results["per_dataset"][model_file.name] = by_ds
    results["models"].append(model_file.name)
print(json.dumps(results, indent=2))
# -

# +
md = ["# MES Benchmarks\n",
      "Auto-generated by `notebooks/kaggle/03_validate.py` on the latest HF dataset + model snapshot.\n"]
for model_name, by_ds in results["per_dataset"].items():
    md.append(f"\n## {model_name}\n")
    md.append("| Dataset | n | Accuracy | AUC | Brier |\n|---|---:|---:|---:|---:|\n")
    for ds_name, r in by_ds.items():
        md.append(f"| {ds_name} | {r['n']} | {r['acc']:.3f} | {r['auc']:.3f} | {r['brier']:.3f} |\n")

Path("benchmarks.md").write_text("".join(md))
Path("benchmarks.json").write_text(json.dumps(results, indent=2))

api.upload_file(path_or_fileobj="benchmarks.md", path_in_repo="benchmarks.md",
                repo_id=HF_MODEL_REPO, commit_message="auto benchmarks")
api.upload_file(path_or_fileobj="benchmarks.json", path_in_repo="benchmarks.json",
                repo_id=HF_MODEL_REPO, commit_message="auto benchmarks json")
print("DONE")
# -
